### ISSUE TITLE
[CSS] rgba is not valid in text-shadow

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-compiler#25]
Hi, 

if I try to use something like: text-shadow: 0 -1px 0 rgba(0,0,0,0.70);
the theme and final app compiles but browser throws two errors at runtime:

App.js:573 Uncaught SyntaxError: Unexpected identifier
index.html:282 Uncaught ReferenceError: App is not defined
    at index.html:282

in App.js there's: this["textShadow"] = [0.0, -1.0, 0.0, unexpected value type: rgba(0,0,0,0.70)]; 
Unexpected identifier 'value'. Expected either a closing ']' or a ',' following an array element

**Comment by carlosrovira** [comment]
some more info from console compilation:

/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/target/javascript/bin/js-debug/App.js
end of list of source files
Mar 06, 2018 1:34:31 PM com.google.javascript.jscomp.LoggerErrorManager println
GRAVE: /Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/target/javascript/bin/js-debug/App.js:579: ERROR - Parse error. ',' expected
this["textShadow"] = [0.0, -1.0, 0.0, unexpected value type: rgba(0,0,0,0.70)];
                                                 ^

IT seems the problem is that when parse, it expects a "," but I think is getting a "." from the "0.70". This is a problem in the CSS Lexer/Parser?

**Comment by aharui** [comment]
This looks like it is Google Closure Compiler complaining about the text "unexpected value type:".  I think that text should not be in App.js.  That line should just read:

this["textShadow"] = [0.0, -1.0, 0.0, rgba(0,0,0,0.70)];

Or maybe leave it as a string to be handled by the framework at runtime:

this["textShadow"] = [0.0, -1.0, 0.0, "rgba(0,0,0,0.70)"];

Or the output should be something like:

this["textShadow"] = [0.0, -1.0, 0.0, 0xC0000000];

Because the compiler knows to convert rgba into hexadecimal with alpha in the higher bits.

**Comment by carlosrovira** [comment]
Hi Alex,

I tried to change to:

text-shadow: 0 1px 0 "rgba(0,0,0,0.70)";
or
text-shadow: 0 1px 0 0xC0000000; 

since this is the syntax used in .css file (the bracket form is the compiler conversion).

But both options are not valid, compilation is ok, and I can see the line in resultant .css, but the results doesn't show any shadow at all.

I think we should get printed in final .css exactly this

text-shadow: 0 1px 0 rgba(0,0,0,0.70);

since if I change the previous line to that, the shadow appears ok in the browser

**Comment by carlosrovira** [comment]
One more thing. Something I didn't say is that changing to what you suggests seems to move the line from App.js to App.css. So the error makes the line goes in bracket format to the .js file. This seems somewhat weird :?

**Comment by aharui** [comment]
In the JS output, some CSS is output twice.  Once in App.js as a data structure for ValuesManager/SimpleCSSValuesImpl and the other in App.css for the browser.  There is some logic that tries to not output certain CSS to App.css because it is not CSS compliant like all of the ClassReferences for beads.  But I think other styles are output twice.  So yes, for sure, the output in App.css should be CSS compliant and be rgba(0,0,0,0.70), but the output in App.js needs to be a valid array of values that the framework will handle correctly.  Converting rgba to hex seems ok in this case.

**Comment by carlosrovira** [comment]
HI Alex, don't understand. Are you saying that conversion from rgba to hex is ok? but that's not working in final css as I said in the previous comment. And in this case, it seems that there's no line in .js (since in fact is not a ClassReference) and is only in .css (what seems ok since is a normal css rule for text-shadow).

**Comment by carlosrovira** [comment]
Thanks Alex, I'll try it as soon as I can :)

**Comment by carlosrovira** [comment]
Hi Alex,
this is strange, since I'm trying the same you use as a test case and is not working for me, in JewelTheme:

.jewel.textbutton, .jewel.textbutton:hover {
  ...
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.7);
}

and when compile JewelExample and try in a browser I get 2 errors in console:

[Error] SyntaxError: Unexpected identifier 'value'. Expected either a closing ']' or a ',' following an array element.
	(función anónima) (App.js:590)
this["textShadow"] = [0.0, -1.0, 0.0, unexpected value type: rgba(0, 0, 0, 0.7)];

**Comment by carlosrovira** [comment]
Hi Alex,

I comes back and tried to use this but is not working. So I'll reopen this bug

**Comment by aharui** [comment]
There is a test in the compiler-jx folder that is working.  See CSSTestSource.css.  Make that test fail and then I will take a look.  Otherwise, verify you have correctly picked up the fix.

**Comment by carlosrovira** [comment]
Hi Alex,

I put in my theme CSS the same line in the test :

text-shadow: 0 -1px 0 rgba(0,0,0,0.70)

And this makes the application build successful, but the problem is at runtime:

this["textShadow"] = [0.0, -1.0, 0.0, unexpected value type: rgba(0, 0, 0, 0.7)];

Does the test a) checks if compiles?, then if b) compiles the app where is used? and then 3) if the output is valid is ok to work at runtime?. I think 1) and 2) are ok, but 3) is failing without doubt

Thanks

**Comment by aharui** [comment]
Yes, the test checks all 3 things.  We had a problem before where you had trouble picking up changes.  The responsibility is on you to validate that you have those changes.   Add a System.out.println to prove the changed code is being called.

-Alex

**Comment by carlosrovira** [comment]
Hi Alex, 
I tried to put System.out.println, but don't know if I put them in wrong way since I don't see anything. In the other way, I make all the things I usually do to ensure I'm with the current code. This time, not only turn off/on my computer, and remove royale in .m2, I as well made a mvn prune dependencies to ensure all is new. As well this made me to agree again with license, download AIR, and more.

This still is failing. I think something is bad in the test that make you think is ok. But I can't do much more to give you evidence of the problem. I as well get other fixings in compiler running (the class reference one), so I know I have the latest running in my mac. I'm entirely convinced this bug is still there. 

To easily see this, try to put the same line you test (text-shadow: 0 -1px 0 rgba(0,0,0,0.70)) in whatever .css you like, compile and try in a browser. You'll see that is not working, if that not happen, I don't know really what could be the problem

thanks

**Comment by aharui** [comment]
Hi Carlos, if you are not seeing any output, that implies there is still something wrong with your setup.  I took the time to add text-shadow to the DataBindingExample and everything worked as expected.  Something is still wrong on your side.

If you look at the commits I made, you should be able to find the new lines of code.  Adding System.out.println before and after those new lines should cause output.  And also add a System.out.println to main() entry point MXMLJSC.java or COMPJSC.java.  That code pretty much as to be running.

**Comment by carlosrovira** [comment]
Hi Alex,
In my latest post I was put prints as you said in JSCSSCompilationSession and CSSRgbaColorPropertyValue, now I do the same in MXMLJSC.java and COMPJSC.java, but I don't see nothing :?

Maybe I'm doing something wrong, I pass maven for "royale-compiler" repo that is 0.9.3-SNAPSHOT, I suppose typedefs and asjs are using that. Then I compile JewelExample and revise output but don't see nothing there. I suppose there's where I should see the printlns right?

**Comment by aharui** [comment]
Hi Carlos,

I forgot that Maven calls the execute() entry point in MXMLJSC and COMPJSC.  Sorry about that.

If you are getting println for the MXMLJSC and in  JSSCSSCompilationSession and CSSRGBaColorPropertyValue then try changing what those files output and make sure that is reflected in the output.

-Alex

**Comment by carlosrovira** [comment]
Hi Alex,
What I said in my last comment in that I put println in *all* those 4 files and I don't see any trace when I launch mvn clean install in JewelExample.

**Comment by aharui** [comment]
Hi Carlos,

Just like last time, that implies that your local changes are not used when compiling an example.  Do you remember what you did to get it working last time?

Clear out the Royale jars from your local Maven repo and re-install the compiler and check file sizes and dates.

Also check the console output and see where it is pulling the compiler.

**Comment by carlosrovira** [comment]
Alex, I think I know what's happening. Although I removed and I'm working with 0.9.3-SNAPSHOT, when I run JewelExample, in .m2 repository I see how maven creates 0.9.2-SNAPSHOT, so it's a problem of poms version not updated. I'll check it now

**Comment by carlosrovira** [comment]
All working now. Now even printlns shows, text-shadow is working. This was tricky, since maven downloads 0.9.2 in the shadow...

I can commit all the files that I changed from "0.9.2" to "0.9.3", but I think it deserves you take a look so I don't change wrong files right?

**Comment by piotrzarzycki21** [comment]
What files did you changed ? I think I have fixed some of those issues in develop yesterday.

**Comment by carlosrovira** [comment]
As I'm doing rebase all the time I'm always synced, even your changes yesterday.
What I missed is the latest merge of 0.9.2 release branches in develop.
With that I don't need to commit nothing, but if I search for 0.9.2 I still see some projects with that version that should be updated in examples (JSON2ASVO and DividedContainerExample)

**Comment by piotrzarzycki21** [comment]
You had 0.9.2 before Alex merge release branch. That's why I'm asking what files did you change - Maybe I missed some of them.
1. I have changed 0.9.2 in some places yesterday 
https://github.com/apache/royale-asjs/commit/34b98d0b4b1fbb7439b66d42984799492d67ca94
https://github.com/apache/royale-typedefs/commit/950f0875968c314c973e88b5af28af09d3b1f2f0
2. Today Alex merge release branch - Check what has happened with my changes - probably they are untouched, but who knows. 

That's how it looks like.

**Comment by carlosrovira** [comment]
I saw your changes yesterday, and I always rebase at the end of a new day (at least) to stay at the top and resolve conflicts (I don't want to resolve all conflicts in a branch the last day, use to be very hard). The problem was that asjs main pom was dictating to use compiler 0.9.2, and that's was fixed just minutes ago when Alex merge release branches. Now as I say I only see JSON2ASVO and DividedContainerExample in 0.9.2 and that should be updated

**Comment by aharui** [comment]
I think it should be safe to update those two projects.  If you can see if they are missing in the parent pom that might be why they did not get auto-updated

**Comment by piotrzarzycki21** [comment]
Just removed from .m2 folder royale. I see that typedefs is being downloaded as 0.9.2, but maybe we have to wait for the build, because windows on Jenkins is offline.
